"""add saju profiles

Revision ID: c36a48832c17
Revises: 8ce2bdc3b619
Create Date: 2026-08-03 16:07:03.591987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36a48832c17'
down_revision: Union[str, Sequence[str], None] = '8ce2bdc3b619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saju_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time', sa.Time(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('calendar_type', sa.String(length=20), nullable=False),
    sa.Column('is_leap_month', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saju_profiles_user_id'), 'saju_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saju_profiles_user_id'), table_name='saju_profiles')
    op.drop_table('saju_profiles')
    # ### end Alembic commands ###
